# Generated by Django 4.2 on 2023-07-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cycle_number",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="rotation_number",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
