# Generated by Django 4.2 on 2023-07-26 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SusuGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_id",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                ("group_name", models.CharField(blank=True, max_length=120, null=True)),
                ("capacity", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "number_of_people",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("slots_left", models.IntegerField(blank=True, default=0, null=True)),
                ("group_description", models.TextField(blank=True, null=True)),
                (
                    "payment_cycle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Yearly", "Yearly"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "rotation_number",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("cycle_number", models.IntegerField(blank=True, default=1, null=True)),
                ("cycle_started", models.BooleanField(default=False)),
                (
                    "group_type",
                    models.CharField(
                        blank=True,
                        choices=[("Private", "Private"), ("Public", "Public")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("group_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "target_amount",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("days_left", models.IntegerField(blank=True, default=0, null=True)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SusuGroupUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Mobile Wallet", "Mobile Wallet"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Payangel Wallet", "Payangel Wallet"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_turn", models.BooleanField(default=False)),
                ("paid", models.BooleanField(default=False)),
                (
                    "paid_amount",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("paid_on", models.DateTimeField(blank=True, null=True)),
                (
                    "momo_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("confirm_payment", models.BooleanField(default=False)),
                ("received", models.BooleanField(default=False)),
                (
                    "receiving_amount",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("receiving_date", models.DateTimeField(blank=True, null=True)),
                (
                    "rotation_number",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("cycle_number", models.IntegerField(blank=True, default=0, null=True)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="susu_group_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SusuPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("vacant", "Vacant"), ("occupied", "Occupied")],
                        max_length=10,
                    ),
                ),
                (
                    "rotation_number",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("cycle_number", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="susu_groups.susugroup",
                    ),
                ),
                (
                    "susu_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="susu_groups.susugroupuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SusuGroupUserReminders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_reminder_on", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                (
                    "rotation_number",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("cycle_number", models.IntegerField(blank=True, default=0, null=True)),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "susu_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="susu_groups.susugroupuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="susugroup",
            name="susu_group_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="susu_group_users",
                to="susu_groups.susugroupuser",
            ),
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "rotation_number",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("cycle_number", models.IntegerField(blank=True, default=0, null=True)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="susu_groups.susugroup",
                    ),
                ),
                (
                    "susu_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="susu_groups.susugroupuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PAY NOW", "PAY NOW"),
                            ("PAID", "PAID"),
                            ("CONFIRM PAID", "CONFIRM PAID"),
                            ("RECEIVE", "RECEIVE"),
                        ],
                        default="PAY NOW",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_for",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("amount", models.CharField(blank=True, max_length=120, null=True)),
                ("days_left", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "rotation_number",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("cycle_number", models.IntegerField(blank=True, default=0, null=True)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_pay_schedule",
                        to="susu_groups.susugroupuser",
                    ),
                ),
                (
                    "user_susu_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pay_schedule_susu_group",
                        to="susu_groups.susugroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvitedMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=120, null=True)),
                ("invitation_sent", models.BooleanField(default=False)),
                ("invitation_accepted", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="susu_groups.susugroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "rotation_number",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("cycle_number", models.IntegerField(blank=True, default=0, null=True)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="susu_groups.susugroup",
                    ),
                ),
                (
                    "susu_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="susu_groups.susugroupuser",
                    ),
                ),
            ],
        ),
    ]
