# Generated by Django 4.2 on 2023-07-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("susu_groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="susugroup",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
