# Generated by Django 4.2 on 2023-07-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("susu_groups", "0002_alter_susugroup_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="susugroupuser",
            name="group_id",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
