# Generated by Django 4.2 on 2023-07-26 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[("GHC", "GHC"), ("USD", "USD"), ("NIRA", "NIRA")],
                        default="GHC",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "balance",
                    models.CharField(blank=True, default=0, max_length=255, null=True),
                ),
                (
                    "bonus",
                    models.CharField(blank=True, default=0, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default=user_profile.models.get_default_profile_image,
                        null=True,
                        upload_to=user_profile.models.upload_image_path,
                    ),
                ),
                ("dob", models.DateTimeField(blank=True, null=True)),
                (
                    "marital_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bank Wallet", "Bank Wallet"),
                            ("Mobile Wallet", "Mobile Wallet"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "momo_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("about_me", models.TextField(blank=True, null=True)),
                (
                    "credit_ranking",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        default=0,
                        max_digits=30,
                        null=True,
                    ),
                ),
                (
                    "payment_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("profile_complete", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=30, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=30, null=True
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default=user_profile.models.get_default_profile_image,
                        null=True,
                        upload_to=user_profile.models.upload_image_path,
                    ),
                ),
                ("dob", models.DateTimeField(blank=True, null=True)),
                (
                    "marital_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("about_me", models.TextField(blank=True, null=True)),
                (
                    "credit_ranking",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        default=0,
                        max_digits=30,
                        null=True,
                    ),
                ),
                (
                    "payment_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("profile_complete", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=30, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=30, null=True
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
